services:
  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - FLASK_ENV=production

  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - ENV=production
      - SITE_BASE_URL=https://artloom.ru

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge